# onfon_media_sms_gateway
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

# CohesityManagementSdk
module OnfonMediaSmsGateway
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.onfonmedia.co.ke/v1/sms'

    # Network Layer Access Key
    @access_key = 'ACCESS_KEY'

    # Used for authentication purpose and pass this parameter in URL encoded format.
    @api_key = 'API_KEY'

    # Used for authentication purpose and pass this parameter in URL encoded format.
    @client_id = 'CLIENT_ID'

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :base_uri
      attr_accessor :access_key
      attr_accessor :api_key
      attr_accessor :client_id
    end
  end
end
