# onfon_media_sms_gateway
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module OnfonMediaSmsGateway
  # Utility class for custom query_parameter authorization.
  class CustomQueryAuth
    # Add custom authentication to the request.
    # @param [HttpRequest] The HttpRequest object to which authentication will
    # be added.
    def self.apply(http_request)
      http_request.add_query_parameter('ApiKey', Configuration.api_key)
      http_request.add_query_parameter('ClientId', Configuration.client_id)
    end
  end
end
