# onfon_media_sms_gateway
#
# This file was automatically generated by
# APIMATIC v2.0 ( https://apimatic.io ).

module OnfonMediaSmsGateway
  # HTTP Methods Enumeration.
  class HttpMethodEnum
    HTTPMETHODENUM = [GET = 'GET'.freeze, POST = 'POST'.freeze,
                      PUT = 'PUT'.freeze, PATCH = 'PATCH'.freeze,
                      DELETE = 'DELETE'.freeze, HEAD = 'HEAD'.freeze].freeze
  end
end
